### ISSUE TITLE
how to add banner at the top of the default container?

### ISSUE THREAD

**Issue by maverickpravin** [coreui/coreui-free-vue-admin-template#136] opened 2018-10-27 11:21 UTC
Thanks for this amazing template! i want to ask if i wanted to add a image  banner at the top of the default container, i have fixed header so when i add a image the page scrolls with the image too.

TIA

**Comment by woothu** [comment] 2018-12-04 08:00
Yes, the header is fixed by default, this is intended behavior, so everything you put inside AppHeader component will also be fixed.

**Closed** 2019-01-07 19:18 UTC
