### ISSUE TITLE
problem in npm run dev in panel

### ISSUE THREAD

**Issue by zshahab91** [coreui/coreui-free-vue-admin-template#38] opened 2017-12-11 07:27 UTC
hi
when run : npm run dev in Vue_Full_Project folder get me error:
Error: ENOENT: no such file or directory, scandir '/Users/sogolmirzajani/Desktop/panel/CoreUI-Vue-master/Vue_Full_Project/node_modules/node-sass/vendor'

how to fixed error?

best regards

**Comment by xidedix** [comment] 2017-12-11 12:38
Hi @zshahab91 
What's your installed version of Node.js?

**Comment by zshahab91** [comment] 2017-12-11 12:44
v6.11.4

**Comment by zshahab91** [comment] 2017-12-11 12:44
@xidedix 
v6.11.4

**Comment by xidedix** [comment] 2017-12-12 12:28
@zshahab91 
Unfortunately I cannot reproduce this issue.
Please try to remove the entire `node_modules` subdirectory, and then reinstall it with` npm i`.
Are there any errors when installing dependencies?

**Comment by cmandesign** [comment] 2017-12-26 12:31
I have the same issue here. i am using Ubuntu 16.04 and my node version is v8.9.1 and npm version is 5.6.0


complete error log : 

 ERROR  Failed to compile with 1 errors                                 15:05:21

 error  in ./src/App.vue

Module build failed: Error: ENOENT: no such file or directory, scandir '/home/soroosh/Downloads/CoreUI-Vue-master/Vue_Full_Project/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/home/soroosh/Downloads/CoreUI-Vue-master/Vue_Full_Project/node_modules/node-sass/lib/extensions.js:128:13)
    at foundBinariesList (/home/soroosh/Downloads/CoreUI-Vue-master/Vue_Full_Project/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/soroosh/Downloads/CoreUI-Vue-master/Vue_Full_Project/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/soroosh/Downloads/CoreUI-Vue-master/Vue_Full_Project/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/soroosh/Downloads/CoreUI-Vue-master/Vue_Full_Project/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/soroosh/Downloads/CoreUI-Vue-master/Vue_Full_Project/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/soroosh/Downloads/CoreUI-Vue-master/Vue_Full_Project/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)

 @ ./node_modules/vue-style-loader!./node_modules/css-loader?{"minimize":false,"sourceMap":false,"alias":{"../img":"../static/img"}}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-7ba5bd90","scoped":false,"hasInlineConfig":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=1&bustCache!./src/App.vue 4:14-431 13:3-17:5 14:22-439
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

> Listening at http://localhost:8080

**Comment by cmandesign** [comment] 2017-12-26 15:25
i found out the problem is because of this line in App.Vue 

<style lang="scss">
`  @import './scss/style';
`  // Import Main styles for this application
</style>

**Comment by mohsenpayro** [comment] 2018-02-11 20:12
i have the same problem here, how did you solve it??

**Comment by woothu** [comment] 2018-12-04 09:35
I'm closing this issue because the issue is obsolete.

**Closed by woothu** 2018-12-04 09:35 UTC
